# Generated by Django 4.2.11 on 2024-05-18 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebChamCong', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('nhanvien', 'Nhân viên')], max_length=20),
        ),
        migrations.CreateModel(
            name='BangChamCong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('luong_ngay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebChamCong.account')),
            ],
        ),
    ]
