# Generated by Django 4.2.13 on 2024-05-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebChamCong', '0004_alter_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bangchamcong',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='bangchamcong',
            name='luong_ngay',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
