# Generated by Django 4.2.13 on 2024-05-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebChamCong', '0005_alter_bangchamcong_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='salary',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bangchamcong',
            name='luong_ngay',
            field=models.IntegerField(null=True),
        ),
    ]
